# Generated by Django 6.1.1 on 2026-09-09 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("unsafe_condition", "Unsafe Condition"),
                            ("unsafe_act", "Unsafe Act"),
                            ("near_miss", "Near Miss"),
                            ("equipment_failure", "Equipment Failure"),
                            ("environmental", "Environmental"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "category_other_detail",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("description", models.TextField()),
                (
                    "reporter_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                (
                    "photo",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("location", models.CharField(max_length=255)),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="core.assignee",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="core.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Closure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("photo", models.FileField(upload_to="closures/")),
                ("closed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closures",
                        to="core.assignee",
                    ),
                ),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closure",
                        to="core.report",
                    ),
                ),
            ],
        ),
    ]
