# Generated by Django 6.1.1 on 2026-09-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_report_closure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="category",
            field=models.CharField(
                choices=[
                    ("unsafe_condition", "Unsafe Condition"),
                    ("unsafe_act", "Unsafe Act"),
                    ("slip_trip_fall", "Slip/Trip/Fall"),
                    ("equipment", "Equipment"),
                    ("chemical", "Chemical"),
                    ("electrical", "Electrical"),
                    ("environmental", "Environmental"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
    ]
