"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    """Populate os.environ from a simple KEY=VALUE .env file, if present."""
    if not path.exists():
        return
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


_load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-lnn+rk-l=5y58y2w&i@0pfw2$u2d0b_f0t%xkqx!*!km#aj)%6",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASE_URL = os.environ.get(
    "DATABASE_URL", "postgres://hse_tool:hse_tool@localhost:5432/hse_tool"
)
_db_url = urlparse(DATABASE_URL)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _db_url.path.lstrip("/"),
        "USER": _db_url.username,
        "PASSWORD": _db_url.password,
        "HOST": _db_url.hostname,
        "PORT": _db_url.port or 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
#
# Served via whitenoise in all environments (#12) so the app doesn't
# depend on a separate static file host/CDN for MVP. `collectstatic`
# populates STATIC_ROOT; whitenoise serves straight from there with
# hashed, far-future-cached filenames in production.

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# The manifest storage whitenoise recommends for production requires
# `collectstatic` to have already run (it looks up a hashed filename
# for every {% static %} reference via a manifest file). Local dev/test
# runs don't run collectstatic, so they fall back to plain whitenoise
# storage which serves files by name straight from STATIC_ROOT/finders
# with no manifest lookup — keeping `runserver`/tests unaffected.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage.CompressedManifestStaticFilesStorage"
            if not DEBUG
            else "whitenoise.storage.CompressedStaticFilesStorage"
        ),
    },
}


# Media files (user uploads, e.g. Report/Closure photos)
# Local filesystem storage is fine for MVP; cloud storage is deferred (#15).

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
#
# Django 6.1's MAILERS setting (replacing the older EMAIL_* settings,
# which this Django version soft-deprecates) configures the "default"
# mailer. Local dev defaults to the console backend so nothing is ever
# sent externally. Production sets DJANGO_EMAIL_BACKEND to the SMTP
# backend and the other DJANGO_EMAIL_* vars for a plain SMTP account
# (see #7) — no credentials are committed here.

_EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)

# The SMTP backend accepts host/port/username/password/use_tls OPTIONS;
# other backends (console, locmem, filebased...) reject unknown options,
# so only pass them through when SMTP is actually selected.
_EMAIL_OPTIONS = (
    {
        "host": os.environ.get("DJANGO_EMAIL_HOST", ""),
        "port": int(os.environ.get("DJANGO_EMAIL_PORT", "587")),
        "username": os.environ.get("DJANGO_EMAIL_HOST_USER", ""),
        "password": os.environ.get("DJANGO_EMAIL_HOST_PASSWORD", ""),
        "use_tls": os.environ.get("DJANGO_EMAIL_USE_TLS", "True") == "True",
    }
    if _EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend"
    else {}
)

MAILERS = {
    "default": {
        "BACKEND": _EMAIL_BACKEND,
        "OPTIONS": _EMAIL_OPTIONS,
    },
}

DEFAULT_FROM_EMAIL = os.environ.get(
    "DJANGO_DEFAULT_FROM_EMAIL", "hse-tool@example.com"
)


# Access-code gating (#10)
# https://docs.djangoproject.com/en/6.1/topics/http/decorators/
#
# Gates the supervisor dashboard (#11) and assignee report detail page
# (#8) without building full user accounts. Valid codes are configured
# here from an env var only — never hardcoded, never stored in the DB.
# Comma-separated; blank/whitespace entries are dropped.

ACCESS_CODES = [
    code.strip()
    for code in os.environ.get("DJANGO_ACCESS_CODES", "").split(",")
    if code.strip()
]
